# Generated by Django 5.0.6 on 2024-12-10 04:07

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_remove_member_points'),
        ('officers', '0002_officer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officers.officer')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('location', models.TextField(verbose_name='Address or location')),
                ('description', models.TextField(verbose_name='description or extra info')),
                ('show_officer_info', models.BooleanField(default=True)),
                ('listed', models.BooleanField(default=True)),
                ('complete', models.BooleanField(default=False)),
                ('points_available', models.IntegerField(default=10)),
                ('attendance_open', models.BooleanField(default=False)),
                ('last_opened_time', models.DateTimeField(null=True)),
                ('current_code', models.CharField(max_length=8, null=True)),
                ('attendance_duration', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officers.officer')),
            ],
            options={
                'ordering': ['date_time', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('subtract', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('for_event', models.BooleanField(default=False)),
                ('for_volunteering', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officers.officer')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('marked', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('point_transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='private.pointtransaction')),
            ],
            options={
                'ordering': ['-event__date_time', 'event__title'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('marked', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('point_transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='private.pointtransaction')),
            ],
            options={
                'ordering': ['-opp__date_time', 'opp__title'],
            },
        ),
        migrations.CreateModel(
            name='VolunteeringOpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('location', models.TextField(verbose_name='Address or location')),
                ('description', models.TextField(verbose_name='description or extra info')),
                ('show_officer_info', models.BooleanField(default=True)),
                ('listed', models.BooleanField(default=True)),
                ('complete', models.BooleanField(default=False)),
                ('points_available', models.IntegerField(default=10)),
                ('max_members', models.PositiveIntegerField(default=0)),
                ('sign_up_open', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(through='private.Attendance', to='members.member')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officers.officer')),
            ],
            options={
                'ordering': ['date_time', 'title'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='opp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.volunteeringopp'),
        ),
    ]
