# Generated by Django 5.0.6 on 2024-12-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_points'),
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members_attended',
            field=models.ManyToManyField(through='private.EventAttendance', to='members.member'),
        ),
    ]
