# Generated by Django 5.0.6 on 2024-12-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_event_members_attended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendance',
            name='marked',
        ),
    ]
