# Generated by Django 5.0.6 on 2024-08-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='default/files/gallery')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('emphasized', models.BooleanField(default=False)),
            ],
        ),
    ]
