# Generated by Django 5.0.6 on 2025-01-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='emphasized',
            new_name='auto_scale',
        ),
    ]
