# Generated by Django 5.0.6 on 2024-10-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_phone_number_member_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='points',
        ),
    ]
